import math

print("\nThis is the script written by Keith DeSantis for Question 1 on Assignment 4.\n")

##### INITIAL VALUES #####

p = 709
a = 2
alicePriv = 17
bobPriv = 41

############################## Part a ##############################

print("Part a:\n")
# Finding Alice's public key
# pub = generator ^ priv mod p
alicePub = (a**alicePriv)%p
print(f"Generator = {a}")
print(f"Alice's Private Key = {alicePriv}")
print(f"Modulus = {p}")
print(f"Alice's Public Key = {a} ^ {alicePriv} mod {p}")
print(f"This exponentiation can be solved using the SQUARE & MULTIPLY algorithm, but in this case the number is small enough to solve outright.")
print(f"Alice's Public Key = {(a**alicePriv)} mod {p}")
print(f"Alice's Public Key is {alicePub}\n\n")

############################## Part b ##############################

print("Part b:\n")
# Finding Bob's public key
# pub = generator ^ priv mod p
bobPub = (a**bobPriv)%p
print(f"Generator = {a}")
print(f"Bob's Private Key = {bobPriv}")
print(f"Modulus = {p}")
print(f"Bob's Public Key = {a} ^ {bobPriv} mod {p}")
print(f"This exponentiation can be solved using the SQUARE & MULTIPLY algorithm, but in this case the number is small enough to solve outright.")
print(f"Bob's Public Key = {a**bobPriv} mod {p}")
print(f"Bob's Public Key is {bobPub}\n\n")

############################## Part c ##############################

print("Part c:\n")
# Find common key generated by Alice and Bob

# Key generated will be generator ^ (alicePriv * bobPriv) mod p

commonKey = (a**(alicePriv*bobPriv))%p

print(f"Generator = {a}")
print(f"Alice's Private Key = {alicePriv}")
print(f"Bob's Private Key = {bobPriv}")
print(f"Modulus = {p}")
print(f"Common key generated by both is {a} ^ ({alicePriv} * {bobPriv}) mod {p}")
print(f"Common key generated by both is {a} ^ ({alicePriv * bobPriv}) mod {p}")
print(f"This exponentiation can be solved using the SQUARE & MULTIPLY algorithm, but in this case the number is small enough to solve outright.")
print(f"Common key generated by both is {a**(alicePriv * bobPriv)} mod {p}")
print(f"Common key generated by both is {commonKey}\n\n")

############################## Part d ##############################

print("Part d:\n")

print("Done on paper...\n\n")